import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import path from "path";

// Geist Sans
const geistSans = localFont({
  src: [
    {
      path: "../fonts/Geist-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/Geist-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "../fonts/Geist-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/Geist-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist-sans",
  display: "swap",
});

// Geist Mono
const geistMono = localFont({
  src: [
    {
      path: "../fonts/GeistMono-Light.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/GeistMono-Regular.woff2",
      weight: "300",
      style: "normal",
    },
    {
      path: "../fonts/GeistMono-SemiBold.woff2",
      weight: "600",
      style: "normal",
    },
    {
      path: "../fonts/GeistMono-Bold.woff2",
      weight: "700",
      style: "normal",
    },
  ],
  variable: "--font-geist-mono",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/favicon.ico", type: "image/x-icon" }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
